#! /bin/sh
#set -x

##SUFFIX=
##PREFIX=
##
####usage()
####{
####    echo -e "\n Usage: $0 -s file's suffix name [eg: -s s S] or -p file's prefix name [eg: -p Makefile makefile]\n"
####    exit 1
####}
####
####if [ $# = 0 ]; then
####    usage
####fi
##
###use cscope-indexer to refresh
##cscope-indexer -r
##if [ $? -eq 1 ]; then
##    echo "cscope-indexer -r failed"
##    rm cscope.files
##    exit 1
##fi
##
##PREVIOUS_OPTION=
##while [ -n "$1" ]
##do
##    case "$1" in
##        -s)
##            PREVIOUS_OPTION="$1"
##            if [ "X$2" != "X" ]; then
##                shift
##            fi
##            ;;
##        -p)
##            PREVIOUS_OPTION="$1"
##            if [ "X$2" != "X" ]; then
##                shift
##            fi
##            ;;
##        -*) #from now, not support other option execupt -s -p
##            echo -e "\n NOTE: from now, not support other option execupt -s -p"
##            usage
##            ;;
##        *)
##            if [ "${PREVIOUS_OPTION}" == "-s" ]; then
##                SUFFIX="${SUFFIX} ${1}"
##            fi
##            if [ "${PREVIOUS_OPTION}" == "-p" ]; then
##                PREFIX="${PREFIX} ${1}"
##            fi
##            shift
##            ;;
##    esac
##done
##
### find files and redirecto to cscope.files
##for suf in ${SUFFIX} ;do
##
##done
##for pre in ${PREFIX} ;do
##    find . -name "$pre*" >> cscope.files
##done
##
### continue
##cscope -q -b -i cscope.files -f cscope.out

find . \( -type f -o -type l \) | \
    egrep -i '\.([chly](xx|pp)*|cc|hh)$' | \
    sed -e '/\/CVS\//d' -e '/\/RCS\//d' -e 's/^\.\///' | \
    sort > cscope.files

find . -name "*.S" >> cscope.files
find . -name "*.s" >> cscope.files
find . -name "Makefile*" >> cscope.files
find . -name "makefile*" >> cscope.files
cscope -q -b -i cscope.files -f cscope.out

exit $?
